### ISSUE TITLE
Homebridge crashing

### ISSUE THREAD

**Issue by EjvindHald** [nicoduj/homebridge-automower#14]
Hi
Thanks for this binding. I am getting some wired problems that Homebridge is crashing after adding your plug-in. I am not 100 % though, because Homebridge is restarting and it has also a now and then problem this evening with a login to a cloud service.
However, it has now happen 2 times in row and both times the problem disappeared when I removed automower plug-in.
Therefore, this question: have you tested your plug-in with the new beta version 0.4.54 which has HAP-nodeJS 0.5.x? - see [link](https://github.com/homebridge/homebridge/issues/2459)
Thanks.

Edit: it seems to be working correct with the latest homebridge beta version. The problem occured if I installed and configured solely through homebridge-config-ui-x. There is no problem if I do a manual install of the plug-in and manual adding to config.json.

**Comment by nicoduj** [comment]
Hi, thanks for feedback.

could you tell me what the error was and the difference in the resulting config file ?

**Comment by EjvindHald** [comment]
It might not be related to your stuff, but instead to the json update done by homebridge-config-ui-x.
I will update this post, when I know more.

**Comment by nicoduj** [comment]
Json update through configUI is made through a template definition handled by the plugin itself, so there might be an error there on my side

**Comment by EjvindHald** [comment]
I think you can close this. A few days back a new version of homebridge-config-ui-x was released. The release notes stated that he fixed a number of issues in the json update.

**Comment by nicoduj** [comment]
Ok, thx. LEt me know if you reproduce some time or if you reminds what was wrong in the config generated so that I can check.
