### ISSUE TITLE
No blocking in case of timeout

### ISSUE THREAD

**Issue by EjvindHald** [nicoduj/homebridge-automower#16]
Today, I suddenly received 'No response' from 30-40 objects in my iPhone Homekit. I looked into the Homebridge log, but the only unusual error message was from automower. It was a timeout from the Huqvarna site. Please ensure that such a problem does not affect Homebridge and other plug-ins.

Another minor thing is that every time an update of automower is installed using the Homebridge-ui-x I received a warning message that there are reference to some deprecated stuff.

Thanks.

**Comment by nicoduj** [comment]
Hi,

Please, could you post your error log and config (refresh settings especially) ?  Does it happen often ? Is it ok afterwards ? I will check, but such information could help, and there is always some drawbacks to return state to homebridge without any response from the device, where you could see some difference between the reality and homekit state. Moreover, is is node, so no multithreading ...

The deprecated is about request, a common http package that was deprecated not so long ago. A lot of dependencies are still based on it.

**Comment by EjvindHald** [comment]
Here is examples from the log:

> `[37m[4/23/2020, 7:56:05 AM][39m [36m[openHAB2-Complete][39m Setting new transformed state for item UdendorTemperatur: 7.94
[37m[4/23/2020, 7:56:19 AM][39m [36m[MQTT_SolvarmeTank][39m Received MQTT: fyrrum/solvarmetemp = 30.800000
[37m[4/23/2020, 7:56:24 AM][39m [36m[HomebridgeAutomower][39m ERROR - getMowers - retrieving mower - read ETIMEDOUT
[37m[4/23/2020, 7:56:27 AM][39m [36m[openHAB2-Complete][39m Received push with new state for item StueplanStuePIRsensornetkontakt: OPEN
[37m[4/23/2020, 7:56:27 AM][39m [36m[openHAB2-Complete][39m Setting new transformed state for item StueplanStuePIRsensornetkontakt: true


[37m[4/23/2020, 8:12:14 AM][39m [36m[openHAB2-Complete][39m Received state: OFF (transformed to false) for Spot vaskerum [KaelderVaskerumLampeudtagVaeg]
[37m[4/23/2020, 8:12:15 AM][39m [36m[Camera-ffmpeg][39m Snapshot from Axis hus haven at 480:270
[37m[4/23/2020, 8:12:16 AM][39m [36m[openHAB2-Complete][39m Received state: CLOSED (transformed to false) for Bev sensor bil [UdenforSojleVestPIRsensor]
[37m[4/23/2020, 8:12:16 AM][39m [36m[openHAB2-Complete][39m Received state: CLOSED (transformed to false) for Bev sensor skur [UdenforCykelskurPIRsensor]
[37m[4/23/2020, 8:12:16 AM][39m [36m[openHAB2-Complete][39m Received state: 8.42 (transformed to 8.42) for Temperatur ude [UdendorTemperatur]
[37m[4/23/2020, 8:12:18 AM][39m [36m[Camera-ffmpeg][39m Snapshot from Axis hus foran at 480:270
[37m[4/23/2020, 8:12:18 AM][39m [36m[HomebridgeAutomower][39m ERROR - getMowers - retrieving mower - connect ETIMEDOUT 54.77.135.173:443
[37m[4/23/2020, 8:13:07 AM][39m [36m[MQTT_SolvarmeLoft][39m Received MQTT: loft/solvarmetemp = 18.700000
[37m[4/23/2020, 8:13:34 AM][39m [36m[openHAB2-Complete][39m Received push with new state for item KaelderFyrrumVandmaalerHomekitInit: ON
[37m[4/23/2020, 8:13:34 AM][39m [36m[openHAB2-Complete][39m Setting new transformed state for item KaelderFyrrumVandmaalerHomekitInit: 1
[37m[4/23/2020, 8:13:35 AM][39m [36m[openHAB2-Complete][39m Received push with new state for item KaelderFyrrumVandmaalerHomekitDelayed: ON
[37m[4/23/2020, 8:13:35 AM][39m [36m[openHAB2-Complete][39m Setting new transformed state for item KaelderFyrrumVandmaalerHomekitDelayed: 1
[37m[4/23/2020, 8:14:27 AM][39m [36m[HomebridgeAutomower][39m ERROR - getMowers - retrieving mower - connect ETIMEDOUT 18.203.53.172:443
[37m[4/23/2020, 8:14:33 AM][39m [36m[openHAB2-Complete][39m Received push with new state for item KaelderFyrrumVandmaalerHomekitInit: OFF`

and snippets from config.json:

>       {
        "platform": "HomebridgeAutomower",
          "email": "myhiddenmailaddress",
          "password": "xxxxxx"
      },

I have not defined any timeout as you can see.

It does not happen so often, but everything was off for 20-30 minutes. 
I saw that the Homebridge Nest plug-in has just today release an update to avoid similar problems in case of problems with login to provider web site.

Thanks.

**Comment by nicoduj** [comment]
NEst change seems to be at startup only. Since this plugin is cached accessory based, it should not delay launch of homebridge at all. What you are experiencing is during updates of status . Will check, the drawback of not waiting during status retrieval is that you will have some delayed information, but once again I will check, thanks for reporting and I agree that it is important to handle this in a better way.

**Comment by nicoduj** [comment]
By the way, are you on latest version ?

**Comment by nicoduj** [comment]
Made a new version that should improve this. However, you will need to clean the cache before restarting homebridge, sorry (use cleanCache option) - see Changelog
