### ISSUE TITLE
Plug-in suddenly missing

### ISSUE THREAD

**Issue by EjvindHald** [nicoduj/homebridge-automower#18]
Hi

I have experienced that sometimes Homebridge simply stops and my iPhone gets no response on all accessories. The error message in the log is saying the homebridge-automower plug-in is not installed. It happened yesterday, and I do not know what triggers this.

When I go into Homebridge Config UI X, I can see that the plug-in is indeed missing. So I simply install the plug-in using Config UI X, and everything works fine again. I do not know why this happens (maybe new release of plug-in?) and therefore I also do not know if this is a problem in automower or Homebridge Config UI X.

However, I never experience this with the other 5 homebridge plug-ins I am using.

Thanks.

**Comment by nicoduj** [comment]
Hi, last update imposed to clean cahced accessories due to service id changes. Next one will force a reinstall since platform name is changed to be consistent with other plugins.

Might be linked, let me know if it happens again.

Please post exact logs in case it happens again

**Comment by nicoduj** [comment]
see #19
