### ISSUE TITLE
Automower status from Siri

### ISSUE THREAD

**Issue by mvoigt1971** [nicoduj/homebridge-automower#20]
Asking Siri: How is the status of Automower?
Possible answers:
- the Automower is mowing
- the Automower is parking.
- the Automower is charging its battery
- the Automower needs help

Asking siri: When will Automower start mowing?
-  Automower is mowing
- The Automower will start today at 16:00
- The Automower will start at 09.07.20, 16:00 Uhr
- The Automower won‘t start mowing

This function will increase the use of the Automower plugin extremely.

**Comment by nicoduj** [comment]
Hi,

thanks for the suggestion. I would also like it to be possible, but unfortunately such interaction with Siri is not possible as far as I know with current APIs.
