### ISSUE TITLE
Add a switch to handle start / stop until further notice

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-automower#21]
Make switchs options and add one to handle start / stop until further notice

**Comment by nicoduj** [comment]
still need to figure the command. /control/park returns no error but does not seem to work (at least when the mower is parked due to adaptiv weather)

**Comment by DougMunford** [comment]
Looks like the newer open API has a feature for this.
https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/readme
Needs a body with "ParkUntilFurtherNotice"

**Comment by nicoduj** [comment]
Yes, Saw that . but I don't use this API since it has rate limit and would involve each user to get an API Key at least, and I fera nobody would be very pleased with that. Still trying however ;)
