### ISSUE TITLE
Select which mowers to use?

### ISSUE THREAD

**Issue by marcus-aa** [nicoduj/homebridge-automower#23]
A manual selection would be nice, as there may be mowers belonging to different homes and should be used by different HB installations.

**Comment by nicoduj** [comment]
Hi, so I understand it is working with multiple mowers (never tested since I have only one). Will try do add an option

**Comment by marcus-aa** [comment]
Hi,
Yes, I have 2 so far but will add 1-2 more in a different location that should not be included in this homebridge.

Autodetection worked fine, but none of the errors they encountered so far has been indicated and start command sometimes needs 2 attempts. Not sure if it is related to multiple machines or not.

**Comment by nicoduj** [comment]
Hi, I have published an update that should address the issues you reported. Let me know .

**Comment by marcus-aa** [comment]
Great, updated and will test!

i also previously got auth errors and was logged out from the app, related? Will see if it returns.

**Comment by nicoduj** [comment]
log errors can happen since it does not support being logged on multiple device at the same time . token are becoming invalid, but the plugin should handle this and reconnect.
