### ISSUE TITLE
Parked also means charging

### ISSUE THREAD

**Issue by marcus-aa** [nicoduj/homebridge-automower#24]
Parked in the charging station should also force the "Charging" indicator to high.

**Comment by nicoduj** [comment]
Hi, it should only be charging if battery level is < 100. else it is not.

**Comment by marcus-aa** [comment]
It was at 68% and increasing so was definitely charging.

**Comment by nicoduj** [comment]
Yes, I saw a problem, should be better with 1.4.1, let me know.
