### ISSUE TITLE
Support mowers from Husqvana branch Gardena

### ISSUE THREAD

**Issue by cschildhorn** [nicoduj/homebridge-automower#28]
Hi, 

there is a branch of Husqvana that is selling mowers as well.

Not sure if it is possible to add support for them as well. There was a homebridge plugin but this seams abandoned and non-functional.

https://github.com/neuhausf/homebridge-gardena-mower#readme

**Comment by nicoduj** [comment]
Hi,

I don't own such mower so it will be a long shot for me, sorry.

**Comment by cschildhorn** [comment]
Ah ok. Thought the API might be not that different and perhaps only a little addon to your plugin https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API#/readme
