### ISSUE TITLE
Refreh timer issue

### ISSUE THREAD

**Issue by A1000000** [nicoduj/homebridge-automower#30]
1.
I think I have a problem with the refresh timer. Due to the constant logins, it looks like Husqvarna always logs me out in the original app or IFTT. If this is related, only the manufacturer can adjust this, of course.
2.
In the Homebridge UI Config for the plugin, I can't set the Auto Refresh to deactivated. Only a numerical value can be set.

**Comment by nicoduj** [comment]
Hi,
Indeed, the plugin connection involves disconnection from the app, can't do anything about that.

If you want to disable the refresh timer, remove the option from the config . I did not check but setting it to 0 should also work as far as I remember
