### ISSUE TITLE
Reason why startStopUntilFurtherNoticeSwitch is stateless?

### ISSUE THREAD

**Issue by tritter** [nicoduj/homebridge-automower#32]
I was wondering why `startStopUntilFurtherNoticeSwitch` is only stateless it is possible to read the value `PARKED_IN_CS` right? For me it would be useful to have the state in homekit too. I could make a PR if you like, just wondering if there is a reason why this is done. Thanks a lot for your efforts!

**Comment by nicoduj** [comment]
Hi,

Indeed, the value of the state should allow to make this switch non stateless. What you expect is that when the mower is parked until further notice, the switch should be off, and when it is only following its schedule, it should be on no matter it is mowing currently or not, right?

**Comment by tritter** [comment]
@nicoduj I expect that when I park the mower 'until further notice' within the Automower-App that the switch is 'ON'. This seems not be the case? So on would be 'PARKED_IN_CS' and off in all other cases? What else is the button supposed to be doing? When I use the switch in the HomeKit-App it sometimes stays on, sometimes not...
